# Generated by Django 3.2.25 on 2024-05-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Cat_image',
            field=models.ImageField(default=True, upload_to='Cat_image/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=True, upload_to='images/'),
        ),
    ]
